Repository bcgov/MOH-ALR, pull requests merged in 2024-02, with the labels that each got.

#485 ALR-911
  src/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Admin_Clerk.md-meta.xml
  src/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Admin_Data_Analyst.md-meta.xml
  src/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Data_Analyst.md-meta.xml
  src/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Investigator.md-meta.xml
  src/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Leadership.md-meta.xml
  src/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Ops_Support_1.md-meta.xml
  src/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Registrar.md-meta.xml
Labels: bugfix

#514 hypercare-ALR-961
  src-access-mgmt/main/default/permissionsetgroups/EHIS_ALR_Leadership_PSG.permissionsetgroup-meta.xml
Labels: Next sprint

#516 GH Workflows Update
  .github/workflows/PR_Code_Deployment.yml
  .github/workflows/PR_Code_Validation.yml
  .github/workflows/QA_Code_Deployment.yml
  .github/workflows/ST_Code_Deployment.yml
Labels: devops
