Repository bcgov/MOH-ALR, pull requests merged in 2024-05, with the labels that each got.

#696 ALR-1429
  src/main/default/objects/Account/fields/Fax.field-meta.xml
Labels: Hotfix

#726 feature-ALR-1311
  src-access-mgmt/main/default/permissionsets/EHIS_CRE_Assessment_Objects_PS.permissionset-meta.xml
  src-temp/main/default/permissionsets/EHIS_CAT_assessment_question_PS.permissionset-meta.xml
  src/main/default/flows/Add_Inspection_Tasks.flow-meta.xml
  src/main/default/flows/Get_Category_List_From_Assessment_Indicator_Definition.flow-meta.xml
  src/main/default/objects/RegulatoryCodeAssessmentInd/AssessmentIndicatorDefinitionCategory__c.field-meta.xml
  src/main/default/objects/RegulatoryCodeAssessmentInd/AssessmentIndicatorDefinitionName__c.field-meta.xml
  src/main/default/objects/RegulatoryCodeAssessmentInd/RegulatoryCodeName__c.field-meta.xml
Labels: SP9

#727 feature-ALR-1259
  src/main/default/classes/FetchAndGenerateCSV.cls
  src/main/default/classes/FetchAndGenerateCSVTest.cls
Labels: SP9

#729 ALR-1291
  src/main/default/classes/BCMOH_Constants.cls
  src/main/default/classes/RCVCreationHelper.cls
  src/main/default/classes/RCVCreationHelper.cls-meta.xml
  src/main/default/classes/RCVCreationHelperTest.cls
  src/main/default/classes/RCVCreationHelperTest.cls-meta.xml
  src/main/default/triggers/Inspectiontrigger.trigger
  src/main/default/triggers/Inspectiontrigger.trigger-meta.xml
Labels: SP9

#737 feature-ALR-1316
  Archive/EHIS_GenerateBusinessLicense_English_6.os-meta.xml
  src-ui/main/default/flexipages/Registrant_Record_Page.flexipage-meta.xml
  src/main/default/omniDataTransforms/EHISDRToCreateTask_1.rpt-meta.xml
  src/main/default/omniDataTransforms/EHISDRToFindExistingTask_1.rpt-meta.xml
  src/main/default/omniScripts/EHIS_GenerateBusinessLicense_English_8.os-meta.xml
  src/main/default/workflows/BusinessLicenseApplication.workflow-meta.xml
Labels: SP9

#806 feature-EHIS-202
  .github/workflows/PR_Code_Deployment.yml
  .github/workflows/PR_Code_Deployment_Hotfix.yml
  .github/workflows/PR_Code_Validation.yml
  .github/workflows/PR_Code_Validation_Hotfix.yml
  ehis-source/app-programworkareaassignment/main/default/objects/Work_Area__c/Work_Area__c.object-meta.xml
  ehis-source/app-programworkareaassignment/main/default/objects/Work_Area__c/compactLayouts/Work_Area_Compact_Layout.compactLayout-meta.xml
  ehis-source/app-programworkareaassignment/main/default/objects/Work_Area__c/fields/Backup_Owner__c.field-meta.xml
  ehis-source/app-programworkareaassignment/main/default/objects/Work_Area__c/fields/Health_Authority__c.field-meta.xml
  ehis-source/app-programworkareaassignment/main/default/objects/Work_Area__c/fields/Primary_Owner__c.field-meta.xml
  ehis-source/app-programworkareaassignment/main/default/objects/Work_Area__c/fields/Public_Group_Id__c.field-meta.xml
  ehis-source/app-programworkareaassignment/main/default/objects/Work_Area__c/fields/Supervisor__c.field-meta.xml
  ehis-source/app-programworkareaassignment/main/default/objects/Work_Area__c/listViews/All.listView-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsetgroups/EHIS_Water_Business_Admin_PSG.permissionsetgroup-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsetgroups/EHIS_Water_Medical_Health_Officer_PSG.permissionsetgroup-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsetgroups/EHIS_Water_Officer_PSG.permissionsetgroup-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsetgroups/EHIS_Water_Public_Health_Engineer_PSG.permissionsetgroup-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsets/EHIS_CRE_Work_Area_PS.permissionset-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsets/EHIS_Manage_System_Admin_User_PS.permissionset-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsets/EHIS_Read_Work_Area_PS.permissionset-meta.xml
  ehis-source/ehis-ui/main/default/flexipages/EHIS_Work_Area_Record_Page.flexipage-meta.xml
  ehis-source/ehis-ui/main/default/layouts/Work_Area__c-Work Area Layout.layout-meta.xml
Labels: EHIS

#813 feature-ALR-1328
  src-access-mgmt/main/default/permissionsets/EHIS_CRE_Business_License_Application_PS.permissionset-meta.xml
  src-access-mgmt/main/default/permissionsets/EHIS_CRE_Business_License_Business_License_Application_PS.permissionset-meta.xml
  src/main/default/flows/Update_Closed_Date_in_BLA.flow-meta.xml
  src/main/default/objects/BusinessLicenseApplication/fields/ClosedDate__c.field-meta.xml
Labels: ALR, SP10

#817 Profile and PSG 191
  ehis-source/ehis-access-mgmt/main/default/permissionsetgroups/EHIS_Water_Public_Health_Engineer_PSG.permissionsetgroup-meta.xml
  ehis-source/ehis-access-mgmt/main/default/profiles/EHIS Standard User.profile-meta.xml
Labels: EHIS

#818 feature-EHIS-207
  ehis-source/core/main/default/objects/Account/compactLayouts/Business_Entity_Compact_Layout.compactLayout-meta.xml
  ehis-source/core/main/default/objects/Account/fields/Other_Type_Details__c.field-meta.xml
  ehis-source/core/main/default/objects/Account/fields/Physical_address__c.field-meta.xml
  ehis-source/core/main/default/objects/Account/recordTypes/Business_Entity.recordType-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsets/EHIS_CRE_Account_PS.permissionset-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsets/EHIS_Manage_System_Admin_User_PS.permissionset-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsets/EHIS_Read_Edit_Account_PS.permissionset-meta.xml
  ehis-source/ehis-ui/main/default/flexipages/EHIS_Business_Entity_Record_Page.flexipage-meta.xml
  ehis-source/ehis-ui/main/default/layouts/Account-Business Entity Page Layout.layout-meta.xml
Labels: EHIS

#821 EHIS-205
  ehis-source/core/main/default/objects/Account/recordTypes/Water_System.recordType-meta.xml
  ehis-source/ehis-access-mgmt/main/default/permissionsets/EHIS_Manage_System_Admin_User_PS.permissionset-meta.xml
  ehis-source/ehis-ui/main/default/flexipages/EHIS_Water_System_Record_Page.flexipage-meta.xml
  ehis-source/ehis-ui/main/default/layouts/Account-Water System Page Layout.layout-meta.xml
Labels: EHIS

#822 EHIS Profile
  ehis-source/ehis-access-mgmt/main/default/profiles/EHIS Standard User.profile-meta.xml
Labels: EHIS
