Repository bcgov/MOH-ALR, pull requests merged in 2025-08, with the labels that each got.

#1603 BCMOHAD-29533 Updated the flow to prevent the duplicate inspection creation
  bcgov-source/app-alr/main/default/flows/InitialCmplianceInspCreation.flow-meta.xml
Labels: bug

#1619 Feature phocs 2076
  bcgov-source/app-phocs/main/default/customPermissions/PHOCSReportingUser.customPermission-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/BLAEvaluationRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/BLAOperatingPermitRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/ConstructionPermitApplication.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/EHISInspectionRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/EHISWaterSourceIntakeRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/EHISWaterSystemRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/EHIS_Business_Entity_Record_Page.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSBusinessLicensePermitRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSComplaintRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSConditionsRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSDocumentChecklistItemRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSDrawingPlanDocumentChecklistRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSDyeTestRequiredRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSDyeTestRequisitionRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSERCPDocumentChecklistItemRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSExemptionsRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSFoodLabTestRequiredRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSFoodRecallRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSFoodTestRequisitionRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSInteractionSummaryRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSLeadWaterTestRequiredRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSLeadWaterTestRequisitionRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSPublicComplaintRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSRadonAirQualityTestRequiredRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSRadonTestRequisitionRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSRegulatoryCodeViolationRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSRegulatoryTransactionFeeRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSReportableIncidentRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSRequestsInquiriesRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSTemporaryFoodService.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSViolationEnforcementActionRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSWaterAdvisoriesRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSWaterLabTestRequisitionRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/permissionsets/PHOCSREADReportingUser.permissionset-meta.xml
  bcgov-source/core/main/default/lwc/accountContactRelatedList/accountContactRelatedList.html
  bcgov-source/core/main/default/lwc/accountContactRelatedList/accountContactRelatedList.js
Labels: phocs-sp10

#1675 2353-changes
  bcgov-source/app-phocs/main/default/flexipages/PHOCSWaterLabTestRequiredRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/flexipages/PHOCSWaterLabTestRequisitionRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/objects/LabTestRequired__c/fields/ReportedOn__c.field-meta.xml
  bcgov-source/app-phocs/main/default/permissionsets/EHISPHOCSCRELabTestRequired.permissionset-meta.xml
  bcgov-source/app-phocs/main/default/permissionsets/EHIS_Manage_System_Admin_User_PS.permissionset-meta.xml
  bcgov-source/app-phocs/main/default/permissionsets/PHOCSREADReportingUser.permissionset-meta.xml
Labels: PHOCS-SP11

#1677 Feature phocs 2131 update field label names
  bcgov-source/core/main/default/objects/Account/fields/Extension__c.field-meta.xml
  bcgov-source/core/main/default/objects/Contact/fields/Extension__c.field-meta.xml
Labels: PHOCS-SP11

#1678 Feature phocs 2298 Add file to Inspection Assessment Indicator
  bcgov-source/app-alr/main/default/flexipages/Inspection_Assessment_Indicator_Record_Page.flexipage-meta.xml
  bcgov-source/app-alr/main/default/layouts/InspectionAssessmentInd-Inspection Assessment Indicator Layout.layout-meta.xml
  bcgov-source/core/main/default/applications/EHIS_Services.app-meta.xml
Labels: PHOCS-SP11

#1679 EHIS-2297 Update ALR's flow to bypass running if it's PHOCS Inspectio…
  bcgov-source/app-alr/main/default/flows/Check_incomplete_tasks_found.flow-meta.xml
Labels: PHOCS-SP11

#1690 EHIS-2331
  bcgov-source/app-phocs/main/default/permissionsets/PHOCSPublicSectorAccessPSL.permissionset-meta.xml
  bcgov-source/core/main/default/objects/Case/fields/SubTopic__c.field-meta.xml
  bcgov-source/core/main/default/objects/Case/recordTypes/PHOCSRequestsInquiries.recordType-meta.xml
Labels: PHOCS-SP11

#1694 EHIS-2325 add new field, update layout, flexipage, PS
  bcgov-source/app-phocs/main/default/flexipages/PHOCSExemptionsRecordPage.flexipage-meta.xml
  bcgov-source/app-phocs/main/default/layouts/BusinessLicenseApplication-PHOCSExemptionsLayout.layout-meta.xml
  bcgov-source/app-phocs/main/default/permissionsets/EHISPHOCSCREBusinessLicenseApplication.permissionset-meta.xml
  bcgov-source/app-phocs/main/default/permissionsets/EHIS_Manage_System_Admin_User_PS.permissionset-meta.xml
  bcgov-source/app-phocs/main/default/permissionsets/PHOCSREADReportingUser.permissionset-meta.xml
  bcgov-source/core/main/default/objects/BusinessLicenseApplication/fields/CareProgram__c.field-meta.xml
  bcgov-source/core/main/default/objects/BusinessLicenseApplication/fields/ResidentialCareProgram__c.field-meta.xml
  bcgov-source/core/main/default/objects/BusinessLicenseApplication/recordTypes/PHOCSExemptions.recordType-meta.xml
Labels: PHOCS-SP11

#1691 EHIS-2169
  bcgov-source/core/main/default/objects/BusinessLicenseApplication/fields/ReasonforApplying__c.field-meta.xml
  bcgov-source/core/main/default/objects/BusinessLicenseApplication/recordTypes/ConstructionPermitApplication.recordType-meta.xml
  bcgov-source/core/main/default/objects/BusinessLicenseApplication/recordTypes/Evaluation.recordType-meta.xml
  bcgov-source/core/main/default/objects/BusinessLicenseApplication/recordTypes/OperatingPermitApplication.recordType-meta.xml
Labels: PHOCS-SP11
